name: 'homebrew-update-action'
description: 'Homebrew update formula file with your homebrew tap.'
author: 'browng-io'
inputs:
  token:
    required: true
    description: 'Personal github token'
  tap_repo:
    required: true
    description: 'Homebrew tap repository'
  template_path:
    required: true
    description: 'Formula file path in the homebrew tap repository.'
  src_repo:
    required: true
    description: 'Your source application repository.'
runs:
  using: 'node16'
  main: 'dist/index.js'
