const ERROR = {
    FILE_PATH_EMPTY: 'FILE_PATH_EMPTY',
    SHA256_EMPTY: 'SHA256_EMPTY',
    VERSION_EMPTY: 'VERSION_EMPTY',
    URL_EMPTY: 'URL_EMPTY',
    CANNOT_READ_FILE: 'CANNOT_READ_FILE', 
}

export { ERROR };